Feat/#2
Soft-Gallery/issue-management-frontEnd pull request #3
Opened 2024-05-16 06:58 UTC by suminl22

## 💬리뷰 참고사항
![KakaoTalk_20240514_232552357](https://github.com/Soft-Gallery/issue-management-frontEnd/assets/83565901/09477625-b706-408e-a7d2-241103c313a1)
위 레퍼런스를 참고해서
![1](https://github.com/Soft-Gallery/issue-management-frontEnd/assets/83565901/885f6682-e1d8-4ef9-9a3a-d367ffd86462)
이렇게 만들었습니다

## #️⃣연관된 이슈

2024-05-16 08:12 UTC, dmstjdhdh requested changes
간단한 리뷰 확인 부탁드리겠습니다~

2024-05-16 08:12 UTC, dmstjdhdh commented on src/pages/LoginPage.tsx
> +    event.preventDefault();
event.preventDefault();를 사용하는 이유에 대해서 설명해주실 수 있나욥

2024-05-16 08:12 UTC, dmstjdhdh commented on src/pages/LoginPage.tsx
> +    display: inline; /* 문장을 인라인 요소로 설정합니다. */
스타일에 있는 주석은 제거해주시면 좋을 것 같습니다!

2024-05-16 08:13 UTC, dmstjdhdh commented
그리고 PR 제목을 적어주심 좋을 것 같고, 상대적으로 레이아웃을 반영하는건, 이후에 이슈가 생긴다면 수정하면 좋을 것 같아요.

2024-05-18 16:57 UTC, suminl22 commented on src/pages/LoginPage.tsx
> +    event.preventDefault();
event.preventDefault()는 JS에서 이벤트의 기본 동작을 막기 위해 사용되는 메서드입니다. 
이벤트의 기본 동작의 예시로, form 제출 시 페이지 자동 새로 고침 동작이 있는데요.
예를 들어, <a> 태그나 form <submit> 태그가 있지요.

이 코드에서는 <a> 태그에 href를 걸지 않아서 관련이 없지만, form이 있어요.
아이디, 비밀번호 입력 후 제출 버튼을 누르면, 로그인 성공하여 main 페이지로 넘어가거나 로그인 실패하여 실패 이유를 화면에 알려줘야 해요.
로그인 실패 시 로그인 입력 화면 위에 새로 고침되지 않고 로그인 오류를 표시하기 위하여 event.preventDefault()를 사용하였습니다 :)

2024-05-18 16:58 UTC, suminl22 commented on src/pages/LoginPage.tsx
> +    display: inline; /* 문장을 인라인 요소로 설정합니다. */
알겠습니다! :)

2024-05-22 15:43 UTC, dmstjdhdh reviewed
리뷰 부탁드리겠습니다!

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/remotes/postLogin.ts
> +      console.log('User Login successfully:', response);
로직 내에 작성된 로그들은 지워주심 좋을 것 같아요~

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/remotes/postLogin.ts
> +      return false;
실패하면, error를 반환하는게 맞지 않을까요?

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/remotes/postSignUp.ts
> +  }
if 문과 switch문중에 if문을 선택한 이유가 궁금해요, 그리고 백엔드 상수에 맞춰서 ROLE_XXXX를 반환하고 api 요청을 하는게 의도가 맞을까요?

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/remotes/postSignUp.ts
> +  };
return하는 타입에 대해서, 위에서 작성된 response 를 반환하는 코드와 비교를 해주셨으면 좋겠습니다!

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/type/types.ts
> +}
각각의 요소가 있고,없고를 조사하기 위해서 타입 요소에 ? 연산자를 쓰셨다면, 이 요소가 존재하는지 안 하는지는 password나, username 의 길이가 0인지, 혹은 '' 인지 확인하는 방식으로 사용하는건 어떨까요?

2024-05-22 15:43 UTC, dmstjdhdh commented on src/feature/auth/type/types.ts
> +  role: string;
중복되는 요소들에 대해서 어떻게 처리할지 고민이 필요할 것 같아요

2024-05-22 15:43 UTC, dmstjdhdh commented on src/pages/LoginPage.tsx
> +    setPasswordVisible(false);
이런건 이후에 커스텀 훅으로 제작하면 가독성이 더 좋아질 것 같아요!

2024-05-23 06:35 UTC, suminl22 commented on src/feature/auth/remotes/postLogin.ts
> +      console.log('User Login successfully:', response);
지웠습니당:)

2024-05-23 06:35 UTC, suminl22 commented on src/feature/auth/remotes/postLogin.ts
> +      return false;
곧 하겠습니다:)

2024-05-23 06:58 UTC, suminl22 commented on src/feature/auth/remotes/postSignUp.ts
> +  };
성공하면 response.data를 반환하도록 수정했습니다, 결과는 true or false 입니다. error 발생하면 error를 반환하도록 수정했습니다.

2024-05-23 06:59 UTC, suminl22 commented on src/feature/auth/type/types.ts
> +}
일단 빠른 진행을 위하여 넘기도록 하겠습니다 :)

2024-05-23 07:01 UTC, suminl22 commented on src/feature/auth/type/types.ts
> +  role: string;
ValidationErrorType을 로직으로 넘기는 방법으로 처리하겠습니다!

2024-05-23 07:01 UTC, suminl22 commented on src/pages/LoginPage.tsx
> +    setPasswordVisible(false);
좋은 방법이네요!

2024-05-23 07:04 UTC, dmstjdhdh commented on src/feature/auth/type/types.ts
> +}
확인했습니다!

2024-05-23 07:04 UTC, dmstjdhdh approved these changes
수고하셨습니다~

2024-05-23 07:09 UTC, merged